FROM centos:7

RUN cat /etc/yum.repos.d/CentOS-Base.repo
RUN sed -i '/^mirrorlist=/d; s/^#baseurl=/baseurl=/' /etc/yum.repos.d/*.repo
#RUN find /etc/yum.repos.d/CentOS-*.repo -type f -exec sed -i 's/mirrorlist\.centos\.org/vault\.centos\.org/g' {} +
RUN find /etc/yum.repos.d/CentOS-*.repo -type f -exec sed -i 's/mirror\.centos\.org/vault\.centos\.org/g' {} +
RUN cat /etc/yum.repos.d/CentOS-Base.repo
RUN yum -y update

RUN yum install -y epel-release \
    && yum install -y https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm \
    && yum install -y \
        git \
        man \
        which \
        git-core-doc \
        make \
        gcc-c++ \
        libevent-devel \
        gsm-devel \
        opus-devel \
        speex-devel \
        openssl-devel \
        python3-devel \
        python3.6-devel \
        hiredis-devel \
        zlib-devel \
        libcurl-devel \
        spandsp-devel \
        bcg729-devel \
        cmake3 \
        codec2-devel \
        flite-devel \
        lame-devel \
        libmpg123-devel \
        libsamplerate-devel \
        mysql-connector-c++-devel \
        mysql-connector-c++ \
        python3-mysqlclient --nogpgcheck \
        rpm-build

# RUN ln -s /usr/lib64/libmysqlcppconn8.so.2 /usr/lib64/libmysqlcppconn.so
RUN ln -s /usr/lib64/libpython3.6m.so /usr/lib64/libpython3.6.so

WORKDIR /

RUN git clone --depth 1 --branch fb https://github.com/hecko/sems.git

WORKDIR /sems

# create RPM
RUN mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
RUN USE_SPANDSP=1 make
RUN make rpmtar
#RUN rpmbuild --define '_with_python 1' -ba pkg/rpm/sems.spec
RUN rpmbuild -ba pkg/rpm/sems.spec
RUN ls -al /root/rpmbuild/RPMS

#RUN USE_SPANDSP=1 make
#RUN USE_SPANDSP=1 make install

# Run SEMS with the specified configuration
CMD ["/usr/local/sbin/sems", "-E", "-f", "/usr/local/etc/sems/sems.conf"]
